language: generic
#sudo: required
os: ubuntu
services: 
        - docker

before_install: 
        - docker build -t ameysontakke1/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true ameysontakke1/docker-react npm run test -- --coverage
